### ISSUE TITLE
【Feature】希望添加一个uniapp的项目路径的配置参数以支持Monorepo

### ISSUE THREAD

**Issue by semmywong** [hb0730/vscode-uniapp-run#24]
在pnpm+monorepo的仓库中，vscode打开的是monorepo工作空间，uniapp只是其中一个项目，这时候如果启动调试就会报错
```
Error: D:\monorepo-demo\manifest.json 不存在
    at getJson (D:\ProgramFiles\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\uni-cli-shared\lib\json.js:30:11)
    at getManifestJson (D:\ProgramFiles\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\uni-cli-shared\lib\manifest.js:31:10)
    at Object.<anonymous> (D:\ProgramFiles\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\vue-cli-plugin-uni\lib\env.js:39:25)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\ProgramFiles\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\vue-cli-plugin-uni\index.js:5:5)
Error: getaddrinfo ENOTFOUND 96f0e031-f37a-48ef-84c7-2023f6360c0a.bspapp.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '96f0e031-f37a-48ef-84c7-2023f6360c0a.bspapp.com'
}
```
报错：`D:\monorepo-demo\manifest.json 不存在`，实际上该文件存在的于`D:\monorepo-demo\apps\uniapp\manifest.json`

**Comment by hb0730** [comment]
启动根据当前工作目录，如果是这样，应该打开`D:\monorepo-demo\apps\uniapp`

**Comment by semmywong** [comment]
> 启动根据当前工作目录，如果是这样，应该打开`D:\monorepo-demo\apps\uniapp`

但是我实际打开的是D:\monorepo-demo目录，因为我这一个是monorepo工程，里面会有多个工程项目，打开多个vscode不方便。如果有一个参数配置可以指定需要启动的uniapp在哪个目录就比较好了

**Comment by semmywong** [comment]
> 启动根据当前工作目录，如果是这样，应该打开`D:\monorepo-demo\apps\uniapp`

目前这个插件如果不是monorepo工程，也就是单项目单仓库的就不会有问题，就是monorepo会有问题

**Comment by semmywong** [comment]
比如这样：

```json
{
    "type": "uniapp-run",
    "request": "launch",
    "name": "Uniapp Run",
    "platform": "mp-weixin",
    "uniapp-dir": "比如这个参数，如果有配置这个参数那么启动时以这个指定的目录uniapp的目录，如果没有指定那就是默认为当前的工作目录"
}
```

**Comment by hb0730** [comment]
1fdbeaa6b16fc7d342319d06a35d38dc1df5a974 已支持
