### ISSUE TITLE
使用cli创建的vite项目怎么启动

### ISSUE THREAD

**Issue by afushui** [hb0730/vscode-uniapp-run#39]
**npx degit dcloudio/uni-preset-vue#vite my-vue3-project**

node:fs:596
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/Users/afushui/studio/vite-demo/uni-demo/manifest.json'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at parseManifestJson (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli-vite/node_modules/@dcloudio/uni-cli-shared/dist/json/manifest.js:13:47)
    at /Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli-vite/node_modules/@dcloudio/uni-shared/dist/uni-shared.cjs.js:504:22
    at initUVueEnv (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli-vite/node_modules/@dcloudio/vite-plugin-uni/dist/cli/uvue.js:16:69)
    at initEnv (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli-vite/node_modules/@dcloudio/vite-plugin-uni/dist/cli/utils.js:144:28)
    at CAC.runDev (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli-vite/node_modules/@dcloudio/vite-plugin-uni/dist/cli/action.js:49:25)
    at CAC.runMatchedCommand (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli-vite/node_modules/cac/dist/index.js:614:34)
    at CAC.parse (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli-vite/node_modules/cac/dist/index.js:541:12)
    at Object.<anonymous> (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli-vite/node_modules/@dcloudio/vite-plugin-uni/dist/cli/index.js:57:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/afushui/studio/vite-demo/uni-demo/manifest.json'
}

Node.js v18.20.0

**Comment by hb0730** [comment]
项目适用于`HBuilderX 可视化界面`创建的项目，运行需要HBuilderX相关环境

**Comment by afushui** [comment]
好的 ！感谢🙏
